project_id = "qyruqeanznhqazkrrxbr"

[functions.admin-login]
verify_jwt = false

[functions.tiktok-webhook]
verify_jwt = false

[functions.tiktok-rss]
verify_jwt = false

[functions.track-ad-click]
verify_jwt = false

[functions.akedly-otp]
verify_jwt = false

[functions.akedly-send-otp]
verify_jwt = false

[functions.akedly-verify-otp]
verify_jwt = false

[functions.send-ad-notification]
verify_jwt = false
